/*$('.c-sort__action').click(function(){
  $('.c-sort__action').children('.icon').addClass('hidden')
  if($(this).children('.icon').hasClass('visible')){
    $(this).children('.icon').toggleClass('sort-down')
  }
  if($(this).children('.icon').hasClass('hidden')){
    $(this).children('.icon').removeClass('hidden')
    $(this).children('.icon').addClass('visible')
  }else{
    $(this).children('.icon').addClass('hidden')
    $(this).children('.icon').removeClass('visible')
  }
})*/